export const PROFILE_LABELS = {
  title: "Профиль",
  saveButton: "Сохранить",
  changeEmailButton: "Изменить почту",
  changePasswordButton: "Изменить пароль",
  loginLabel: "Логин",
  nameLabel: "Имя",
  lastNameLabel: "Фамилия",
  emailLabel: "Email",
  genderLabel: "Пол",
  timezoneLabel: "Часовой пояс",
  verifiedEmailTooltip: "Почта подтверждена",
  verifiedEmailAriaLabel: "Почта подтверждена",
  emailModalTitle: "Изменение почты",
  newEmailLabel: "Новая почта",
  currentPasswordLabel: "Текущий пароль",
  passwordModalTitle: "Изменение пароля",
  newPasswordLabel: "Новый пароль",
  confirmPasswordLabel: "Повторите пароль",
  cancelButton: "Отмена",
  profileUpdateOk: "Данные профиля обновлены",
  profileUpdateFail: "Не удалось обновить данные профиля",
  profileUpdateError: "Произошла ошибка при обновлении данных",
  passwordUpdateOk: "Пароль успешно изменен",
  passwordUpdateFail: "Не удалось изменить пароль",
  passwordUpdateError: "Произошла ошибка при изменении пароля",
  emailUpdateOk: "Почта обновлена. Отправили письмо для подтверждения.",
  emailUpdateWarning: "Почта обновлена, но письмо не отправилось. Повторите отправку позже.",
  emailUpdateFail: "Не удалось изменить почту",
  emailUpdateError: "Произошла ошибка при изменении почты",
  requiredName: "Имя обязательно для заполнения",
  requiredTimezone: "Выберите часовой пояс",
  requiredNewEmail: "Введите новую почту",
  invalidEmail: "Некорректный email",
  requiredCurrentPassword: "Введите текущий пароль",
  requiredNewPassword: "Введите новый пароль",
  requiredConfirmPassword: "Повторите новый пароль",
  invalidCurrentPassword: "Неверный текущий пароль",
  emailConflict: "Этот email или login уже используется",
  emailUnchanged: "Укажите новый email",
  tooLongName: "Слишком длинное имя",
  tooLongEmail: "Слишком длинный email",
  tooLongPassword: "Слишком длинный пароль",
  minPassword: "Минимум 6 символов",
  passwordMismatch: "Пароли не совпадают",
} as const;

export const GENDER_OPTIONS = [
  { value: "male", label: "Мужской" },
  { value: "female", label: "Женский" },
];
