export const MAX_NAME_LENGTH = 255;
export const MAX_MILEAGE_KM = 99999.99;

export const shoesLabels = {
  title: "Обувь",
  eyebrow: "Спортивный профиль",
  subtitle:
    "Ведите ротацию тренировочных пар, контролируйте их пробег и заранее получайте уведомления о лимите.",
  backButton: "Назад в профиль",
  overviewLabel: "Сводка по обуви",
  overviewLoading: "Данные загружаются",
  overviewUnavailable: "Данные недоступны",
  totalPairsLabel: "Пар в ротации",
  limitedPairsLabel: "С лимитом пробега",
  notifiedPairsLabel: "С уведомлениями",
  createSectionTitle: "Добавить пару",
  createSectionDescription:
    "Укажите узнаваемое название и ресурс пары. Текущий пробег будет собираться из тренировочных отчетов.",
  nameLabel: "Название пары",
  nameHint: "Например, Nike Pegasus 41 или Соревновательные.",
  mileageLimitInputLabel: "Лимит пробега, км",
  mileageLimitHint: "Необязательно. Можно указать значение от 0 до 99 999,99 км.",
  inputPlaceholder: "Nike Pegasus",
  mileageLimitPlaceholder: "Лимит пробега, км",
  addButton: "Добавить пару",
  listTitle: "Ротация обуви",
  listDescription: "Сравнивайте фактический пробег с ресурсом каждой пары.",
  pairCountOne: "пара",
  pairCountFew: "пары",
  pairCountMany: "пар",
  editButton: "Редактировать",
  editSectionTitle: "Редактирование пары",
  saveButton: "Сохранить",
  cancelButton: "Отмена",
  emptyTitle: "Ротация пока пуста",
  emptyText: "Добавьте первую пару, чтобы учитывать пробег в тренировочных отчетах.",
  emptyAction: "Добавить первую пару",
  loadingText: "Загружаем обувь...",
  loadErrorTitle: "Не удалось загрузить обувь",
  loadErrorDescription: "Проверьте соединение и повторите попытку.",
  retryButton: "Повторить",
  helperText: "Название, ресурс и каналы уведомлений для новой пары.",
  nameRequired: "Введите название.",
  nameTooLong: "Название длиннее 255 символов.",
  mileageInvalid: "Пробег должен быть числом от 0 до 99999.99.",
  mileageSectionLabel: "Пробег пары",
  mileageRemainingLabel: "До лимита",
  mileageReachedLabel: "Лимит достигнут",
  mileageNotConfiguredLabel: "Лимит пробега не задан",
  currentMileageLabel: "Текущий пробег",
  mileageLimitLabel: "Лимит",
  notificationsLabel: "Оповещения",
  notificationsLegend: "Уведомления о лимите",
  notificationsHint: "Сообщим, когда пробег пары превысит указанный лимит.",
  notificationAvailable: "Доступен",
  notificationUnavailable: "Недоступен",
  notificationChecking: "Проверяем",
  noNotificationsLabel: "Без уведомлений",
  mileageUnset: "не задан",
  notificationsOff: "выкл",
  emailNotification: "Email",
  telegramNotification: "Telegram",
  notificationAvailabilityLoading: "Проверяем доступность канала уведомлений.",
  emailNotificationUnavailable: "Подтвердите почту в профиле, чтобы включить Email.",
  telegramNotificationUnavailable: "Привяжите Telegram в профиле, чтобы включить Telegram.",
  saveOk: "Обувь добавлена.",
  updateOk: "Обувь обновлена.",
  deleteButton: "Удалить",
  deleteConfirm: "Удалить обувь?",
  deleteOk: "Обувь удалена.",
  loadFail: "Не удалось загрузить список обуви.",
  saveFail: "Не удалось сохранить обувь.",
  updateFail: "Не удалось обновить обувь.",
  deleteFail: "Не удалось удалить обувь.",
} as const;
