export const MAX_NAME_LENGTH = 255;
export const MAX_MILEAGE_KM = 99999.99;

export const shoesLabels = {
  title: "Обувь",
  inputPlaceholder: "Nike Pegasus",
  mileageLimitPlaceholder: "Лимит пробега, км",
  addButton: "Добавить",
  listTitle: "Список обуви",
  editButton: "Редактировать",
  saveButton: "Сохранить",
  cancelButton: "Отмена",
  emptyText: "Пока нет обуви.",
  loadingText: "Загрузка...",
  helperText: "Название и настройки уведомлений.",
  nameRequired: "Введите название.",
  nameTooLong: "Название длиннее 255 символов.",
  mileageInvalid: "Пробег должен быть числом от 0 до 99999.99.",
  currentMileageLabel: "Текущий пробег",
  mileageLimitLabel: "Лимит",
  notificationsLabel: "Оповещения",
  mileageUnset: "не задан",
  notificationsOff: "выкл",
  emailNotification: "Email",
  telegramNotification: "Telegram",
  notificationAvailabilityLoading: "Проверяем доступность канала уведомлений.",
  emailNotificationUnavailable: "Подтвердите почту в профиле, чтобы включить Email.",
  telegramNotificationUnavailable: "Привяжите Telegram в профиле, чтобы включить Telegram.",
  saveOk: "Обувь добавлена.",
  updateOk: "Обувь обновлена.",
  deleteButton: "Удалить",
  deleteConfirm: "Удалить обувь?",
  deleteOk: "Обувь удалена.",
  loadFail: "Не удалось загрузить список обуви.",
  saveFail: "Не удалось сохранить обувь.",
  updateFail: "Не удалось обновить обувь.",
  deleteFail: "Не удалось удалить обувь.",
} as const;
