export const PLAN_TEXT = {
  header: {
    title: "План тренировок",
    description:
      "Ниже — записи плана из базы (сортировка по дате и порядку сессии). Для загрузки нового файла воспользуйтесь кнопкой ниже.",
  },
  actions: {
    dashboard: "На главную",
    addDay: "Добавить день",
    reload: "Обновить план",
    importExcel: "Загрузить план из Excel",
    importDiary: "Загрузить дневник из Excel",
    backToPlan: "Обратно к плану",
    upload: "Загрузить",
  },
  filter: {
    onlyWithoutReports: "Только без отчетов",
  },
  table: {
    workload: "Нагрузка",
    workloadTag: "Рабочая",
    date: "Дата",
    task: "Задание",
    comment: "Комментарий",
    report: "Отчет",
    reportTag: "Заполнен",
    reportMissingTag: "Нет отчета",
    todayTag: "Сегодня",
    actions: "Действия",
    editTooltip: "Редактировать день",
    editAria: (date: string) => `Редактировать день ${date}`,
    shiftTooltip: "Сдвинуть план с этой даты",
    shiftAria: (date: string) => `Сдвинуть план с ${date}`,
    diaryTooltip: "Открыть дневник",
    diaryAria: (date: string) => `Открыть дневник на ${date}`,
  },
  editor: {
    titleCreate: "Добавить день",
    titleEdit: "Редактировать день",
    save: "Сохранить",
    cancel: "Отмена",
    dateLabel: "Дата",
    dateLockedByReport: "Дата заблокирована: по этому дню уже заполнен дневник.",
    workloadLabel: "Нагрузка",
    workoutLabel: (index: number) => `Тренировка ${index}`,
    deleteWorkoutAria: (index: number) => `Удалить тренировку ${index}`,
    taskLabel: "Задание",
    commentLabel: "Комментарий",
    addWorkout: "Добавить тренировку",
    deleteDay: "Удалить день",
  },
  shift: {
    title: "Сдвинуть план",
    fromDateLabel: "Начать с даты",
    directionLabel: "Направление",
    directionForward: "Вперед",
    directionBackward: "Назад",
    daysLabel: "Дней",
    save: "Сдвинуть",
    cancel: "Отмена",
    summary: (fromDate: string) => `Будут сдвинуты все тренировки плана начиная с ${fromDate}.`,
  },
  confirm: {
    deleteWorkoutTitle: "Удалить тренировку?",
    deleteWorkoutWithReport: "При удалении тренировки будет удален связанный отчет.",
    deleteWorkoutSimple: "Удалить тренировку?",
    deleteDayTitle: "Удалить день?",
    deleteDayWithReports: "Удалятся все тренировки дня и связанные отчеты.",
    deleteDaySimple: "Удалятся все тренировки дня.",
    okDelete: "Удалить",
    cancel: "Отмена",
  },
  messages: {
    loadFailed: "Не удалось загрузить записи плана",
    loadError: "Произошла ошибка при загрузке плана",
    fileRequired: "Выберите файл Excel",
    importFailed: "Не удалось загрузить план",
    importRequestError: "Ошибка запроса",
    importWithErrors: (inserted: number, issuesCount: number) =>
      `Загружено: ${inserted}, замечаний: ${issuesCount}`,
    importSuccess: (inserted: number) => `Загружено строк: ${inserted}`,
    dateRequired: "Укажите дату",
    dateExists: "Эта дата уже есть в плане",
    fillWorkouts: "Заполните все тренировки",
    dayNotFound: "День не найден",
    dateLockedByReport: "Нельзя изменить дату дня с заполненным дневником",
    shiftInvalid: "Укажите количество дней для сдвига",
    shiftNotFound: "Не найдены тренировки для сдвига",
    shiftHasReports: "Нельзя сдвинуть план: в переносимом диапазоне уже есть заполненный дневник",
    shiftTargetExists: "Нельзя сдвинуть назад: в целевом диапазоне уже есть тренировки",
    shiftFailed: "Не удалось сдвинуть план",
    shiftServerError: "Ошибка сервера при сдвиге плана. План не изменен.",
    shiftError: "Ошибка при сдвиге плана",
    shiftSuccess: (daysCount: number) => `Сдвинуто дней плана: ${daysCount}`,
    invalidWorkouts: "Некорректные данные тренировок",
    saveFailed: "Не удалось сохранить день",
    saveError: "Ошибка при сохранении дня",
    daySaved: "День сохранен",
    deleteFailed: "Не удалось удалить день",
    deleteError: "Ошибка при удалении дня",
    dayDeleted: "День удален",
  },
  importPage: {
    title: "Импорт плана из Excel",
    description:
      "Файл должен содержать колонки «Дата», «Задание», «Комментарий» (первая строка — заголовки). Используется только первый лист.",
    dragText: "Перетащите файл сюда или кликните для выбора",
    dragHint:
      "Поддерживается .xlsx. При повторной загрузке строки добавятся как новая версия (старые не обновляются).",
    resultTitle: "Результат импорта",
    resultSummary: (importId: number, inserted: number, skipped: number) =>
      `Импорт #${importId}: добавлено ${inserted}, пропущено ${skipped}.`,
    failedTitle: "Импорт не выполнен",
    detailsTitle: "Детали:",
    headersTitle: "Найденные заголовки:",
    rowErrors: "Ошибки строк:",
    rowWarnings: "Предупреждения:",
    rowError: (row: number, message: string) => `Строка ${row}: ${message}`,
  },
} as const;
