export const RECORDS_LABELS = {
  title: "Мои рекорды",
  subtitle: "Заполните дистанции, по которым у вас есть рекорды. Остальные можно оставить пустыми.",
  alertTitle: "Как заполнять",
  alertText:
    "Формат времени: ЧЧ:ММ:СС или ММ:СС. Если время указано, дата обязательна. Пустое время удаляет запись при сохранении.",
  distanceLabel: "Дистанция",
  timeLabel: "Время",
  dateLabel: "Дата",
  raceNameLabel: "Название забега",
  raceCityLabel: "Город",
  protocolLabel: "Ссылка на протокол",
  timePlaceholder: "00:00:00",
  datePlaceholder: "ДД.ММ.ГГГГ",
  raceNamePlaceholder: "Название забега",
  raceCityPlaceholder: "Город",
  protocolPlaceholder: "https://",
  saveButton: "Сохранить",
  loadingText: "Загрузка...",
  loadFail: "Не удалось загрузить рекорды.",
  saveOk: "Рекорды сохранены.",
  saveFail: "Не удалось сохранить рекорды.",
  invalidTime: "Проверьте формат времени.",
  invalidDate: "Укажите корректную дату для заполненных записей.",
  invalidUrl: "Ссылка на протокол слишком длинная.",
  invalidRaceName: "Название забега не должно превышать 255 символов.",
  invalidRaceCity: "Город не должен превышать 255 символов.",
} as const;
