import type { RoleMeta } from "../types/adminUsersTypes";

export const ADMIN_USERS_LABELS = {
  title: "Пользователи",
  subtitle: "Список зарегистрированных пользователей и их текущих ролей.",
  invitesButton: "Приглашения",
  dashboardButton: "В кабинет",
  recordsButton: "Рекорды",
  competitionsButton: "Соревнования",
  actionsMenuButton: "Действия пользователя",
  roleButton: "Роль",
  passwordButton: "Пароль",
  clearTrainingDataButton: "Очистить план/дневник",
  deleteButton: "Удалить",
  disableButton: "Отключить",
  enableButton: "Включить",
  saveButton: "Сохранить",
  cancelButton: "Отмена",
  userColumn: "Пользователь",
  genderColumn: "Пол",
  loginColumn: "Логин",
  roleColumn: "Роль",
  createdAtColumn: "Создан",
  lastActiveAtColumn: "Последняя активность",
  statusColumn: "Статус",
  actionsColumn: "Действия",
  activeStatus: "Активен",
  disabledStatus: "Отключен",
  roleModalTitle: "Сменить роль",
  passwordModalTitle: "Сменить пароль",
  newPasswordLabel: "Новый пароль",
  confirmPasswordLabel: "Повторите пароль",
  selectRolePlaceholder: "Выберите роль",
  selectRoleRequired: "Выберите роль",
  newPasswordRequired: "Введите новый пароль",
  confirmPasswordRequired: "Повторите пароль",
  passwordMismatch: "Пароли не совпадают",
  roleUserMissing: "Не выбран пользователь для смены роли.",
  passwordUserMissing: "Не выбран пользователь для смены пароля.",
  roleUpdateOk: "Роль обновлена.",
  roleUpdateFail: "Не удалось обновить роль.",
  passwordUpdateOk: "Пароль обновлен.",
  passwordUpdateFail: "Не удалось обновить пароль.",
  statusUpdateFail: "Не удалось обновить статус.",
  clearTrainingDataUpdateOk: "План и дневник пользователя очищены.",
  clearTrainingDataUpdateFail: "Не удалось очистить план и дневник пользователя.",
  deleteUpdateOk: "Пользователь удален.",
  deleteUpdateFail: "Не удалось удалить пользователя.",
  userEnabled: "Пользователь включен.",
  userDisabled: "Пользователь отключен.",
  disableConfirmText: "Пользователь не сможет входить в систему до обратного включения.",
  clearTrainingDataConfirmTitle: "Очистить план и дневник пользователя",
  clearTrainingDataConfirmText:
    "Будут без восстановления удалены план, импорты плана, отчеты тренировок, вес и восстановление. Аккаунт, роль, рекорды и обувь останутся.",
  deleteConfirmTitle: "Удалить пользователя",
  deleteConfirmText: "Аккаунт и связанные данные пользователя будут удалены без восстановления.",
  unauthorized: "Нужно войти в систему.",
  forbidden: "Недостаточно прав для выполнения действия.",
  invalidPayload: "Некорректные данные.",
  invalidUserId: "Некорректный идентификатор пользователя.",
  notFound: "Пользователь не найден.",
  cannotDisableSelf: "Нельзя отключить собственного пользователя.",
  cannotDeleteAdmin: "Администратора нельзя удалить.",
  unknownRole: "Не задана",
  maleGender: "Мужской",
  femaleGender: "Женский",
} as const;

export const ROLE_META: Record<string, RoleMeta> = {
  admin: { label: "Администратор", color: "geekblue" },
  athlete: { label: "Атлет", color: "green" },
  coach: { label: "Тренер", color: "purple" },
};

export const ROLE_OPTIONS = [
  { value: "admin", label: "Администратор" },
  { value: "coach", label: "Тренер" },
  { value: "athlete", label: "Атлет" },
];

export const PASSWORD_MIN_LENGTH = 6;
