export const PLAN_TEXT = {
  header: {
    title: "План тренировок",
    description:
      "Ниже — записи плана из базы (сортировка по дате и порядку сессии). Для загрузки нового файла воспользуйтесь кнопкой ниже.",
  },
  actions: {
    dashboard: "На главную",
    addDay: "Добавить день",
    reload: "Обновить план",
    importExcel: "Загрузить план из Excel",
  },
  filter: {
    onlyWithoutReports: "Только без отчетов",
  },
  table: {
    workload: "Нагрузка",
    workloadTag: "Рабочая",
    date: "Дата",
    task: "Задание",
    comment: "Комментарий",
    report: "Отчет",
    reportTag: "Заполнен",
    editColumnTitle: "",
    editTooltip: "Редактировать день",
    editAria: (date: string) => `Редактировать день ${date}`,
    diary: "Дневник",
    diaryTooltip: "Открыть дневник",
    diaryAria: (date: string) => `Открыть дневник на ${date}`,
  },
  editor: {
    titleCreate: "Добавить день",
    titleEdit: "Редактировать день",
    save: "Сохранить",
    cancel: "Отмена",
    dateLabel: "Дата",
    workloadLabel: "Нагрузка",
    workoutLabel: (index: number) => `Тренировка ${index}`,
    deleteWorkoutAria: (index: number) => `Удалить тренировку ${index}`,
    taskLabel: "Задание",
    commentLabel: "Комментарий",
    addWorkout: "Добавить тренировку",
    deleteDay: "Удалить день",
  },
  confirm: {
    deleteWorkoutTitle: "Удалить тренировку?",
    deleteWorkoutWithReport: "При удалении тренировки будет удален связанный отчет.",
    deleteWorkoutSimple: "Удалить тренировку?",
    deleteDayTitle: "Удалить день?",
    deleteDayWithReports: "Удалятся все тренировки дня и связанные отчеты.",
    deleteDaySimple: "Удалятся все тренировки дня.",
    okDelete: "Удалить",
    cancel: "Отмена",
  },
  messages: {
    loadFailed: "Не удалось загрузить записи плана",
    loadError: "Произошла ошибка при загрузке плана",
    dateRequired: "Укажите дату",
    dateExists: "Эта дата уже есть в плане",
    fillWorkouts: "Заполните все тренировки",
    dayNotFound: "День не найден",
    invalidWorkouts: "Некорректные данные тренировок",
    saveFailed: "Не удалось сохранить день",
    saveError: "Ошибка при сохранении дня",
    daySaved: "День сохранен",
    deleteFailed: "Не удалось удалить день",
    deleteError: "Ошибка при удалении дня",
    dayDeleted: "День удален",
  },
} as const;
