export const REGISTER_TEXT = {
  eyebrow: "Новый аккаунт",
  title: "Создайте аккаунт участника",
  subtitle: "Роль и права доступа уже настроены в вашем персональном приглашении.",
  formLabel: "Форма регистрации",
  requiredHint: "Все поля обязательны, кроме фамилии.",
  nameLabel: "Имя",
  namePlaceholder: "Иван",
  nameRequired: "Введите имя",
  nameMin: "Имя должно содержать не менее 2 символов",
  nameMax: "Имя должно содержать не более 255 символов",
  lastNameLabel: "Фамилия (необязательно)",
  lastNamePlaceholder: "Иванов",
  lastNameMax: "Фамилия должна содержать не более 255 символов",
  genderLabel: "Пол",
  genderRequired: "Выберите пол",
  loginLabel: "Логин",
  loginPlaceholder: "runner",
  loginRequired: "Введите логин",
  loginMin: "Логин должен содержать не менее 3 символов",
  loginMax: "Логин должен содержать не более 64 символов",
  emailLabel: "Email",
  emailPlaceholder: "runner@example.com",
  emailRequired: "Введите email",
  emailInvalid: "Некорректный email",
  emailMax: "Email должен содержать не более 255 символов",
  timezoneLabel: "Часовой пояс",
  timezonePlaceholder: "Выберите часовой пояс",
  timezoneRequired: "Выберите часовой пояс",
  passwordLabel: "Пароль",
  passwordPlaceholder: "Минимум 6 символов",
  passwordHint: "Используйте не менее 6 символов. Пароль можно показать кнопкой в поле.",
  passwordRequired: "Введите пароль",
  passwordMin: "Минимум 6 символов",
  submit: "Создать аккаунт",
  existingAccount: "Уже есть аккаунт?",
  login: "Войти",
  inviteRequired: "Регистрация доступна только по приглашению.",
  inviteNoticeTitle: "Нужна персональная ссылка",
  inviteNotice:
    "Откройте ссылку из приглашения тренера или администратора — в ней уже закреплены ваша роль и доступ.",
  inviteHelp: "Если ссылка потерялась или не открывается, запросите новое приглашение.",
  backToLogin: "Вернуться ко входу",
  inviteInvalid: "Приглашение не найдено.",
  inviteUsed: "Приглашение уже использовано.",
  inviteExpired: "Срок действия приглашения истек.",
  userExists: "Аккаунт с таким email или логином уже существует.",
  registerFailed: "Не удалось завершить регистрацию, попробуйте ещё раз.",
  registerSuccess: "Аккаунт создан, входим...",
  autoLoginFailed: "Регистрация успешна, но не удалось войти. Попробуйте войти вручную.",
  requestError: "Произошла ошибка. Попробуйте ещё раз.",
  loadingTitle: "Подготавливаем регистрацию",
  loadingDescription: "Проверяем ссылку приглашения и загружаем форму.",
} as const;

export const GENDER_OPTIONS = [
  { value: "male", label: "Мужской" },
  { value: "female", label: "Женский" },
];

export const REGISTER_FIELD_IDS = {
  name: "register-name",
  lastName: "register-last-name",
  gender: "register-gender",
  genderLabel: "register-gender-label",
  login: "register-login",
  email: "register-email",
  timezone: "register-timezone",
  password: "register-password",
} as const;

export const REGISTER_TITLE_ID = "register-title";
export const REGISTER_INVITE_NOTICE_TITLE_ID = "register-invite-notice-title";
