export const REGISTER_TEXT = {
  title: "Регистрация",
  subtitle: "Создайте новый аккаунт, чтобы получить доступ к панели и планам.",
  nameLabel: "Имя",
  namePlaceholder: "Иван",
  nameRequired: "Введите имя",
  lastNameLabel: "Фамилия",
  lastNamePlaceholder: "Иванов",
  lastNameMax: "Фамилия слишком длинная",
  genderLabel: "Пол",
  genderRequired: "Выберите пол",
  loginLabel: "Логин",
  loginPlaceholder: "Ваш логин",
  loginRequired: "Введите логин",
  loginMin: "Логин должен содержать не менее 3 символов",
  emailLabel: "Почта",
  emailPlaceholder: "Ваш email",
  emailRequired: "Введите email",
  emailInvalid: "Некорректный email",
  timezoneLabel: "Часовой пояс",
  timezonePlaceholder: "Выберите часовой пояс",
  timezoneRequired: "Выберите часовой пояс",
  passwordLabel: "Пароль",
  passwordPlaceholder: "********",
  passwordRequired: "Введите пароль",
  passwordMin: "Минимум 6 символов",
  confirmPasswordLabel: "Подтвердите пароль",
  confirmPasswordRequired: "Подтвердите пароль",
  confirmPasswordMismatch: "Пароли не совпадают",
  submit: "Зарегистрироваться",
  existingAccount: "Уже есть аккаунт?",
  login: "Войти",
  inviteRequired: "Регистрация доступна только по приглашению.",
  inviteNotice: "Регистрация доступна только по пригласительной ссылке.",
  backToLogin: "Вернуться ко входу",
  inviteInvalid: "Приглашение не найдено.",
  inviteUsed: "Приглашение уже использовано.",
  inviteExpired: "Срок действия приглашения истек.",
  registerFailed: "Не удалось завершить регистрацию, попробуйте ещё раз.",
  registerSuccess: "Аккаунт создан, входим...",
  autoLoginFailed: "Регистрация успешна, но не удалось войти. Попробуйте войти вручную.",
  requestError: "Произошла ошибка. Попробуйте ещё раз.",
} as const;

export const GENDER_OPTIONS = [
  { value: "male", label: "Мужской" },
  { value: "female", label: "Женский" },
];
